package com.example.springboothelperproject.enums;

/**
 * @author atiQue
 * @since 17'Jul 2022 at 12:27 AM
 */

public enum BookType {
    Fiction,
    Nonfiction,
    Action_and_adventure,
    Art_or_architecture,
    Alternate_history,
    Autobiography,
    Anthology,
    Biography,
    Chick_lit,
    Business_economics,
    Children,
    Crafts_hobbies,
    Classic,
    Cookbook,
    Comic_book,
    Diary,
    Coming_of_age,
    Dictionary,
    Crime,
    Encyclopedia,
    Drama,
    Guide,
    Fairytale,
    Health_fitness,
    Fantasy,
    History,
    Graphic_novel,
    Home_and_garden,
    Historical_fiction,
    Humor,
    Horror,
    Journal,
    Mystery,
    Math,
    Paranormal_romance,
    Memoir,
    Picture_book,
    Philosophy,
    Poetry,
    Prayer,
    Political_thriller,
    Religion_spirituality_and_new_age,
    Romance,
    Textbook,
    Satire,
    True_crime,
    Science_fiction,
    Review,
    Short_story,
    Science,
    Suspense,
    Self_help,
    Thriller,
    Sports_and_leisure,
    Western,
    Travel,
    Young_adult,
    ;
}
